# Generated by Django 4.1.4 on 2023-02-24 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_serie', models.CharField(max_length=120)),
                ('temporada', models.IntegerField(max_length=2)),
                ('episodio', models.IntegerField(max_length=3)),
                ('streaming', models.CharField(choices=[('prime_video', 'Prime Video'), ('netflix', 'Netflix'), ('hbo_max', 'HBO Max'), ('disney+', 'Disney+'), ('star+', 'Star+'), ('fox', 'Fox'), ('paramout+', 'Paramout+'), ('amc', 'AMC'), ('não_oficial', 'Não Oficial')], max_length=50)),
                ('data_assistir_serie', models.DateField()),
                ('status', models.CharField(choices=[('em_breve', 'Em Breve'), ('assistindo', 'Assistindo'), ('pausado', 'Pausado'), ('finalizada', 'Finalizada'), ('cancelado', 'Cancelado')], max_length=50)),
            ],
        ),
    ]
